### ISSUE TITLE
Is there any Docker image?

### ISSUE THREAD

**Issue by mariushosting** [RishiBakshii/Baatchit-Modern-Chat-Application#1]
Docker image when?

**Comment by RishiBakshii** [comment]
> Docker image when?
> 

I will make one docker image asap then it will be available most probably tomorrow

**Comment by RishiBakshii** [comment]
> Docker image when?

I will make one docker image tomorrow asap, then it will be available and thankyou for raising an issue here

**Comment by RishiBakshii** [comment]
> Docker image when?



> > Docker image when?
> 
> I will make one docker image tomorrow asap, then it will be available and thankyou for raising an issue here

hi, here to give an update on docker image of this project. So i have been working on this and most of the part is done but i just to configure some things out and should be done in very minimal time

**Comment by RishiBakshii** [comment]
hi @mariushosting the docker image is availabe now i dockerized the app using docker compose but if you want to run individual backend and frontend then you can also do that by using individual docker files for frontend and backend.

The readme.md of this repo is also updated and reflects the instructions for setting up this project for docker so i will be closing this issue now

Thankyou
